site_name: Documentation
site_url: https://yaptide.github.io/deploy/
repo_url: https://github.com/yaptide/deploy
repo_name: yaptide/deploy
copyright: Copyright &copy; 2023 the Yaptide team
title: Deploy documentation

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
- Home:
  - Overview: index.md
  - Maintenance: maintenance.md
  - Simulators: simulators.md
  - Cloud deploy: ansible.md

plugins:
- search
- git-revision-date-localized
