- name: Deploy yaptide
  hosts: "{{ variable_host | default('yaptide') }}"
  gather_facts: false
  roles:
    - role: setup
      tags: setup
    - role: backend
      tags: backend
    - role: frontend
      tags: frontend
