- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Check if frontend repo exists
  ansible.builtin.stat:
    path: '{{ backend_repo_workdir }}'
  register: frontend_repo_status

- name: Check if docker pip package is installed
  ansible.builtin.pip:
    name: docker
  check_mode: true
  register: frontend_docker_installation_status
  ignore_errors: true


- name: Recursively remove directory
  become: true
  ansible.builtin.file:
    path: "{{ frontend_repo_workdir }}"
    state: absent
