- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: Kill and remove frontend containers
  become: true
  community.docker.docker_container:
    name: '{{ item }}'
    image: '{{ item }}'
    state: absent
  loop:
    - node
    - nginx
  when: '"docker-ce" in ansible_facts.packages'

- name: Recursively remove directory
  become: true
  ansible.builtin.file:
    path: "{{ frontend_repo_workdir }}"
    state: absent
