- name: Setup
  when: ansible_connection != 'local'
  block:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Remove docker pip package
      ansible.builtin.pip:
        name: docker
        state: absent
      when: '"python3-pip" in ansible_facts.packages'

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Remove packages
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        autoremove: true
        state: absent

    - name: Stop and disable docker service
      ansible.builtin.systemd:
        state: stopped
        name: docker
        enabled: false

    - name: Remove docker-ce
      ansible.builtin.apt:
        name: docker-ce
        autoremove: true
        state: absent

    - name: Remove docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: absent
