# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Install necessary packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
