# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    state: present

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present

- name: Start and enable fail2ban service
  ansible.builtin.systemd:
    state: started
    name: fail2ban
    enabled: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Run apt update and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    update_cache: true

- name: Start and enable docker service
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
